= Informe TP Base de Datos II: hospital
Martín Galvarini <13.martingalva@gmail.com>; Lorenzo Paparo <lolopaparo@gmail.com>; Gianluca Zeolla <gianluze14@gmail.com>; Lucas Manfredi <lucasmanfredij@gmail.com>; Juan_Ignacio Mussino <juani_mussino@hotmail.com>
v1, {docdate}. Docente Hernan Rondelli (COM-08)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

El texto debe ser breve, conciso, simple, y directo. Se debe incluir
sólo lo relevante que ayude a entender el trabajo práctico.

Se recomiendan oraciones y párrafos cortos.

Por último, no olvidar utilizar signos de puntuación y checkear la
ortografía.

== Introducción

El trabajo practico como segundo parcial de la materia "Base de datos II"

es la creacion de una base de datos tanto en sql, go y json; sobre un hospital. 

Esta debe de incluir informacion de pacientes, medicos, turnos, obras sociales 

consultorio y deversa informacion adicional. Esta debera contar con distintos 

Stored Procedures que trabajen con esa base de datos como: 

- Stored Procedures: 
* Generacion de turnos disponibles. 
* Reservas de turnos. 
* Cancelacion de turnos.
* Atencion de turnos.
* Liquidacion para obras sociales.
* Envio de mails a pacientes.


== Descripción

//En esta sección pueden incluirse las dificultades que tuvieron, las
//soluciones encontradas, las decisiones que se fueron tomando a lo largo
//del trabajo práctico, y las cuestiones de diseño que consideren
//importantes.

//También, se puede incluir una descripción general del programa—cómo
//funciona.

Atravez  de este trabajo nos encontramos con distintos obstaculos. 
Muchos de estos se debieron a la poca experiencia en los lenguajes 
que debian ser utilizados tanto en json, go y asciidoc. 
Dividimos muy bien las tareas entre los integrantes del grupo para poder entender  
cada uno de los distintos tipos de escritura haciendo que uno se ocupe 
de el json, otro del asciidoc y todos pusieron de su parte para entender la sintaxis de go. 
Tambien algunos de nosotros tuvimos problemas con entender GitLab y como conectarse 
ya sea desde el git bash como desde la virtual machine de alpine. 
Uno de los mayores obstaculos que tuvimos fueron los Stored procedures 
los cuales nos dieron muchos problemas en cuanto a su logica y su complicada sintaxis. 





== Implementación

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde.

Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
breve descripción, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos.

También se puede incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.
