= Informe TP Base de Datos II: hospital
Martín Galvarini <13.martingalva@gmail.com>; Lorenzo Paparo <lolopaparo@gmail.com>; Gianluca Zeolla <gianluze14@gmail.com>; Lucas Manfredi <lucasmanfredij@gmail.com>; Juan_Ignacio Mussino <juani_mussino@hotmail.com>
v1, {docdate}. Docente Hernan Rondelli (COM-08)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

El trabajo practico como reemplazo del segundo parcial de la materia "Base de datos II"

consiste en la creacion de una base de datos relacional sql y otra no relacional en json (con la libreria de boltdb); 

sobre un hospital. Ambas seran ejecutadas mediante un programa en lenguaje go. La base de datos sql debera contar con distintos 

caracteristicas: 

 -Tablas a crear para la db SQL:
*Pacientes.
*Mediques.
*Consultorios.
*Agendas.
*Turnos.
*Reprogramaciones.
*Errores.
*Coberturas.
*Obras sociales.
*Liquidaciones cabecera.
*Liquidaciones detalle.
*Envios email.

 -Stored Procedures y triggers: 
*Generacion de turnos disponibles. 
*Reservas de turnos. 
*Cancelacion de turnos.
*Atencion de turnos.
*Liquidacion para obras sociales.
*Envio de mails a pacientes.

== Descripción

Dividimos las tareas entre los integrantes del grupo para poder entender  

cada uno, los distintos tipos de lenguajes y entre todos pusimos de nuestra parte para completar el archivo de 

go (postgres), y en especial la implementacion de las ditintas librerias nuevas trabajadas.
 

Lo primero que hicimos fue crear la base de datos sql por fuera de go. Esto sirvio para podeer

visualizar mejor como iba a funcionar nuestro sistema, las keys que ibamos a necesitar y 

poder probar los distintos triggers y stored procedures.

A traves de este trabajo nos encontramos con distintos obstaculos. 

Muchos de estos se debieron a la poca experiencia en los lenguajes 

que debian de ser utilizados tanto en json y go.


El lenguaje go resulto nos ser tan complejo, pero en si tuvimos que comprender conceptos que tal vez

no habiamos trabajado en las otras materias cursadas, como el manejo de las fechas y la conexion a 

postgres. Con esto ultimo lo que mas tuvimos que investigar era como pasar los parametros del go a las 

procedure dentro del postgres y como mostrar los resultados de los mismos.


Otro de los mayores obstaculos que tuvimos fueron los Stored procedures 

los cuales nos dieron muchos problemas en cuanto a su logica y su complicada sintaxis. 

Consideramos que algunos de esos eran demasiado complejos para nuestros conocimientos y 

termiamos atrasandonos demasiado.


Al final pudimos completar el tp, creando la base de datos con todas sus tablas y sus atributos; 

sus Stored procedures con las caracteristicas pedidas; todo esto hecho y testado en postgres sql y luego pasado a go.

Tambien pudimos hacer la base de datos con Json que, al tratarse de una tarea mucho menos compleja, 

pudo salir con mayor facilidad y ayudo a comprender de que se trataban las bases de datos no relacionales 

y las difrerencias con las ya trabajadas en clase. 

== Implementación

.Codigo para manejar los errores de go
[source, go]
----
if err != nil {
		log.Fatal(err)
	}
----

.Conexion a una base de datos sql por postgres
[source, go]
----
func dbConnection()(*sql.DB, error){
    db, err := sql.Open("postgres", "user=postgres host=localhost dbname=Hospital sslmode=disable")
	if err != nil{
       log.Fatal(err)
	}
	return db, nil
}
----

.Creación de la base de datos llamada hospital
[source, go]
----
func crearDB() {
	db, err := sql.Open("postgres", "user=postgres host=localhost dbname=postgres sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	_, err = db.Exec("create DATABASE Hospital")

	if err != nil {
		log.Fatal(err)
	}
}
----

.Descubrimos esta manera de pasar un string de una fecha (pasada por el usuario) a un time.Time
[source, go]
----
t, err := time.Parse("2006-01-02", fecha_turno)
if err != nil {
	fmt.Println("Error al parsear la fecha:", err)
	return
}		
----

.Lectura de un bucket de bytes de un archivo db para poder mostrarlo en go
[source, go]
----
func ReadUnique(db *bolt.DB, bucketName string, key []byte) ([]byte, error) {
    var buf []byte

    // abre una transacción de lectura
    err := db.View(func(tx *bolt.Tx) error {
        b := tx.Bucket([]byte(bucketName))
        buf = b.Get(key)
        return nil
    })

    return buf, err
}
----

	
== Conclusiones


Durante el desarrollo de esta aplicación pudimos llegar a distintos aprendizajes cada uno, como lo  

fueron las maneras en que se debe organizar un grupo de programadores para dividir las tareas, o como 

complementarse para sacar el maximo provecho de las caracteristicas de cada uno.

Pudimos ver de una manera clara las diferencias entre una base de datos relacional y no relacional.

Tambien aprendimos como es la experiencia de la creacion de una base de datos tan grande y compleja, 

por lo menos comparandola con lo que habiamos trabajado previamente en la cursada, y lograr que esta pueda 

pasar las pruebas exigidas por este TP.
