= Informe TP Base de Datos II: hospital
Martín Galvarini <13.martingalva@gmail.com>; Lorenzo Paparo <lolopaparo@gmail.com>; Gianluca Zeolla <gianluze14@gmail.com>; Lucas Manfredi <lucasmanfredij@gmail.com>; Juan_Ignacio Mussino <juani_mussino@hotmail.com>
v1, {docdate}. Docente Hernan Rondelli (COM-08)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

El trabajo practico como reemplazo del segundo parcial de la materia "Base de datos II"

consiste en la creacion de una base de datos relacional sql y otra no relacional en json (utilizando librerias de boltdb); sobre un hospital.

Ambas seran ejecutadas mediante un programa en lenguaje go y deberan de incluir informacion de pacientes, medicos,

turnos, obras sociales y consultorios, entre otras cosas. La base de datos sql debera contar con distintos 

Stored Procedures y triggers como: 

- Stored Procedures y triggers: 
* Generacion de turnos disponibles. 
* Reservas de turnos. 
* Cancelacion de turnos.
* Atencion de turnos.
* Liquidacion para obras sociales.
* Envio de mails a pacientes.


== Descripción

//En esta sección pueden incluirse las dificultades que tuvieron, las
//soluciones encontradas, las decisiones que se fueron tomando a lo largo
//del trabajo práctico, y las cuestiones de diseño que consideren
//importantes.

//También, se puede incluir una descripción general del programa—cómo
//funciona.


A traves de este trabajo nos encontramos con distintos obstaculos. 

Muchos de estos se debieron a la poca experiencia en los lenguajes 

que debian de ser utilizados tanto en json, go y asciidoc. 

Dividimos las tareas entre los integrantes del grupo para poder entender  

cada uno, los distintos tipos de escritura, haciendo que uno ocupe 

del json, otro del asciidoc y entre todos pusimos de nuestra parte para completar el archivo de 

go (postgres), y en especial la implementacion de las ditintas librerias nuevas trabajadas. 

Tambien algunos de nosotros tuvimos problemas con entender GitLab y como conectarse 

ya sea desde el git bash como desde la virtual machine de alpine. 

Uno de los mayores obstaculos que tuvimos fueron los Stored procedures 

los cuales nos dieron muchos problemas en cuanto a su logica y su complicada sintaxis. 


Al final hicimos todo lo que pudimos, creando la base de datos con todas sus tablas y sus atributos; 

sus Stored procedures con las caracteristicas pedidas; todo esto hecho y testado en postgres sql y luego pasado a go.

Tambien pudimos hacer la base de datos con Json que, al tratarse de una tarea mucho menos compleja, 

pudo salir con mayor facilidad y ayudo a comprender de que se trataban las bases de datos no relacionales 

y las difrerencias con las ya trabajadas en clase. 

== Implementación

//En esta sección se incluye el código fuente correctamente formateado—y
//comentado, si corresponde.

=== Aqui esta el codigo de ambas tamblas (Relcional y noRelacional)

[source, go]
----
include::archivo.go[]
----

	
== Conclusiones

//Aquí van algunas reflexiones acerca del proceso de desarrollo del

//trabajo realizado, y de los resultados obtenidos.

//También se puede incluir una conclusión final de producto terminado.

//Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.

Durante el desarrollo de esta aplicación pudimos llegar a distintos aprendizajes cada uno, como lo  

fueron las maneras en que se debe organizar un grupo de programadores para dividir las tareas, o como 

complementarse para sacar el maximo provecho de las caracteristicas de cada uno.

Pudimos ver de una manera clara las diferencias entre una base de datos relacional y no relacional.

Tambien aprendimos como es la experiencia de la creacion de una base de datos tan grande y compleja, 

por lo menos comparandola con lo que habiamos trabajado previamente en la cursada, y lograr que esta pueda 

pasar varias de las pruebas exigidas por este TP. 

